### ISSUE TITLE
Possível melhoria na manipulação de animações e transições

### ISSUE THREAD

**Issue by Leokuma** [satoLG/rpg_char_profile_gen#7]
https://github.com/JSquadders/rpg_char_profile_gen/blob/c91fadc34bbd6f49db46fa5bd827d015ace4d526/js/form.js#L100

Não poderia acessar diretamente a propriedade? Assim:

    personagem.imagem, personagem.perfil

---------

https://github.com/JSquadders/rpg_char_profile_gen/blob/c91fadc34bbd6f49db46fa5bd827d015ace4d526/js/accordion.js#L43-L53

Para evitar usar `setTimeout()` ao chamá-la, `mostrarPerfil()` poderia retornar uma `Promise` que se resolve no [transitionend](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/transitionend_event) ou no [onanimationend](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onanimationend).

**Comment by satoLG** [comment]
> Não poderia acessar diretamente a propriedade? Assim:
> 
> `personagem.imagem, personagem.perfil`

A resposta é sim, senhor @Leokuma

**Comment by satoLG** [comment]
> Para evitar usar setTimeout() ao chamá-la, mostrarPerfil() poderia retornar uma Promise que se resolve no transitionend ou no onanimationend.

Estou refatorando aos poucos, então eu devo mudar isso também, mas o motivo principal de usar o `setTimeOut` é que esse tempo de 4.750 milissegundos serve pra acompanhar o áudio que toca. A função `mostrarPerfil` precisa começar no meio do áudio, num ponto específico, pra ficar do jeito que quero.

**Comment by satoLG** [comment]
https://github.com/JSquadders/rpg_char_profile_gen/blob/c91fadc34bbd6f49db46fa5bd827d015ace4d526/css/index.css#L281-L283

Eu sincronizo a animação da sanfona de certa forma com o tempo da transição no CSS. Mas o fim da animação da sanfona também acontece no meio do áudio, então não serviria como ponto de início da função... ou serviria, mas ai eu precisaria dar mais um `setTimeOut` de qualquer forma.

O problema é que eu quis deixar as animações sincronizadas de forma teatral e artística (rs), acho que não vai ter como evitar um temporizador em algum ponto.

**Comment by satoLG** [comment]
@Leokuma Depois eu te mostro a animação acontecendo aqui pra você entender, acho que você não viu ainda rs

**Comment by Leokuma** [comment]
Ah, entendi. Eu vi rapidamente o `setTimeout` e as transições e concluí precipitadamente que o timeout era por causa das animações. Analisando o código com calma, não faz sentido a conclusão que tirei (o `setTimeout()` estaria no lugar errado, se fosse o caso).

> O problema é que eu quis deixar as animações sincronizadas de forma teatral e artística (rs), acho que não vai ter como evitar um temporizador em algum ponto.

Sim.

Acabei pesquisando a solução de um problema que não existia e aprendendo algo novo. Avise-me se precisar promisificar alguma animação.

**Comment by Leokuma** [comment]
[promiseAnimation.htm](https://gist.github.com/Leokuma/85c8e9cac109574ee84ce5bfa742064b)

Criei esse snippet para demonstrar como se controla o término de uma animação via `Promise`. Também comparei o uso de `Promise`, `Promise.then()` e `async/await`.

**Comment by satoLG** [comment]
> [promiseAnimation.htm](https://gist.github.com/Leokuma/85c8e9cac109574ee84ce5bfa742064b)
> 
> Criei esse snippet para demonstrar como se controla o término de uma animação via `Promise`. Também comparei o uso de `Promise`, `Promise.then()` e `async/await`.

Não só é legal o esquema do `transitionend`, etc... pra criar eventos ligados a animações, mas esse exemplo que você fez é muito bom pra mostrar o funcionamento das Promises.
